# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_capture_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1297, 679)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.recordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.recordBtn.setGeometry(QtCore.QRect(640, 50, 141, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.recordBtn.setPalette(palette)
        self.recordBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.recordBtn.setAutoRepeatDelay(298)
        self.recordBtn.setObjectName("recordBtn")
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setGeometry(QtCore.QRect(460, 50, 141, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.stopBtn.setPalette(palette)
        self.stopBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stopBtn.setAutoRepeatDelay(298)
        self.stopBtn.setObjectName("stopBtn")
        self.recordingStatusEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.recordingStatusEdit.setGeometry(QtCore.QRect(460, 110, 141, 25))
        self.recordingStatusEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.recordingStatusEdit.setReadOnly(True)
        self.recordingStatusEdit.setObjectName("recordingStatusEdit")
        self.recordingStatusLbl = QtWidgets.QLabel(self.centralwidget)
        self.recordingStatusLbl.setGeometry(QtCore.QRect(470, 130, 121, 21))
        self.recordingStatusLbl.setObjectName("recordingStatusLbl")
        self.camera1ImageLbl = QtWidgets.QLabel(self.centralwidget)
        self.camera1ImageLbl.setGeometry(QtCore.QRect(30, 170, 331, 321))
        self.camera1ImageLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.camera1ImageLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera1ImageLbl.setLineWidth(2)
        self.camera1ImageLbl.setText("")
        self.camera1ImageLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.camera1ImageLbl.setObjectName("camera1ImageLbl")
        self.camera2ImageLbl = QtWidgets.QLabel(self.centralwidget)
        self.camera2ImageLbl.setGeometry(QtCore.QRect(370, 170, 331, 321))
        self.camera2ImageLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.camera2ImageLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera2ImageLbl.setLineWidth(2)
        self.camera2ImageLbl.setText("")
        self.camera2ImageLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.camera2ImageLbl.setObjectName("camera2ImageLbl")
        self.camera2Lbl = QtWidgets.QLabel(self.centralwidget)
        self.camera2Lbl.setGeometry(QtCore.QRect(380, 490, 311, 21))
        self.camera2Lbl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.camera2Lbl.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.camera2Lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camera2Lbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.camera2Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.camera2Lbl.setObjectName("camera2Lbl")
        self.camera1Lbl = QtWidgets.QLabel(self.centralwidget)
        self.camera1Lbl.setGeometry(QtCore.QRect(30, 490, 331, 21))
        self.camera1Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.camera1Lbl.setObjectName("camera1Lbl")
        self.quitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.quitBtn.setGeometry(QtCore.QRect(460, 530, 141, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 233, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 233, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 233, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.quitBtn.setPalette(palette)
        self.quitBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.quitBtn.setAutoRepeatDelay(298)
        self.quitBtn.setObjectName("quitBtn")
        self.previewBtn = QtWidgets.QPushButton(self.centralwidget)
        self.previewBtn.setGeometry(QtCore.QRect(280, 50, 141, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 185, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 185, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 185, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.previewBtn.setPalette(palette)
        self.previewBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previewBtn.setAutoRepeatDelay(298)
        self.previewBtn.setObjectName("previewBtn")
        self.camera3ImageLbl = QtWidgets.QLabel(self.centralwidget)
        self.camera3ImageLbl.setGeometry(QtCore.QRect(710, 170, 331, 321))
        self.camera3ImageLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.camera3ImageLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera3ImageLbl.setLineWidth(2)
        self.camera3ImageLbl.setText("")
        self.camera3ImageLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.camera3ImageLbl.setObjectName("camera3ImageLbl")
        self.camera3Lbl = QtWidgets.QLabel(self.centralwidget)
        self.camera3Lbl.setGeometry(QtCore.QRect(720, 490, 311, 21))
        self.camera3Lbl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.camera3Lbl.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.camera3Lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camera3Lbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.camera3Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.camera3Lbl.setObjectName("camera3Lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.recordBtn.setText(_translate("MainWindow", "Record"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.recordingStatusLbl.setText(_translate("MainWindow", "Recording Status"))
        self.camera2Lbl.setText(_translate("MainWindow", "Camera 2"))
        self.camera1Lbl.setText(_translate("MainWindow", "Camera 1"))
        self.quitBtn.setText(_translate("MainWindow", "Quit"))
        self.previewBtn.setText(_translate("MainWindow", "Preview"))
        self.camera3Lbl.setText(_translate("MainWindow", "Camera 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
