# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'track_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import det_n_trk

from queue import Queue
import threading

STOP_CMND = "StopCmnd"
START_CMND = "StartCmnd"
QUIT_CMND = "QuitCmnd"
IDLE_CMND = "IdleCmnd"


cmnd_q = Queue()
status_q = Queue()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1980, 1136))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.video = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.video.setGeometry(QtCore.QRect(50, 40, 1000, 1000))
        self.video.setMinimumSize(QtCore.QSize(0, 0))
        self.video.setMaximumSize(QtCore.QSize(2000, 2000))
        self.video.setFrameShape(QtWidgets.QFrame.Box)
        self.video.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video.setLineWidth(4)
        self.video.setText("")
        self.video.setObjectName("video")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(50, 1040, 1001, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(32, 74, 135);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(530, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(0, 530, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(0, 1020, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(1030, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(1200, 50, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(32, 74, 135);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(1200, 120, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(1260, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(1370, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(1530, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(1720, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.inText = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.inText.setGeometry(QtCore.QRect(1200, 150, 40, 800))
        self.inText.setMaximumSize(QtCore.QSize(40, 800))
        self.inText.setObjectName("inText")
        self.inferredText = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.inferredText.setGeometry(QtCore.QRect(1280, 150, 40, 800))
        self.inferredText.setMaximumSize(QtCore.QSize(40, 800))
        self.inferredText.setObjectName("inferredText")
        self.trackIdText = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.trackIdText.setGeometry(QtCore.QRect(1360, 150, 100, 800))
        self.trackIdText.setMaximumSize(QtCore.QSize(100, 800))
        self.trackIdText.setObjectName("trackIdText")
        self.nameText = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.nameText.setGeometry(QtCore.QRect(1500, 150, 150, 800))
        self.nameText.setMaximumSize(QtCore.QSize(150, 800))
        self.nameText.setObjectName("nameText")
        self.centerText = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.centerText.setGeometry(QtCore.QRect(1690, 150, 150, 800))
        self.centerText.setMaximumSize(QtCore.QSize(150, 800))
        self.centerText.setObjectName("centerText")
        self.startButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.startButton.setGeometry(QtCore.QRect(1290, 980, 127, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(91)
        sizePolicy.setVerticalStretch(41)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(91, 41))
        self.startButton.setStyleSheet("background-color: rgb(115, 210, 22);")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.stopButton.setGeometry(QtCore.QRect(1460, 980, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(91)
        sizePolicy.setVerticalStretch(41)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(91, 41))
        self.stopButton.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.stopButton.setObjectName("stopButton")
        self.quitButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.quitButton.setGeometry(QtCore.QRect(1620, 980, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(91)
        sizePolicy.setVerticalStretch(41)
        sizePolicy.setHeightForWidth(self.quitButton.sizePolicy().hasHeightForWidth())
        self.quitButton.setSizePolicy(sizePolicy)
        self.quitButton.setMinimumSize(QtCore.QSize(91, 41))
        self.quitButton.setStyleSheet("background-color: rgb(245, 121, 0);")
        self.quitButton.setObjectName("quitButton")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        pixmap = QtGui.QPixmap("OperVu-logo.jpg") # Setup pixmap with the OperVu logo
        pixmap = pixmap.scaled(self.video.width(), self.video.height(), QtCore.Qt.KeepAspectRatio) # Scale pixmap
        self.video.setPixmap(pixmap) # Set the pixmap onto the label

        self.f_timer = QtCore.QTimer()
        self.f_timer.setInterval(100)
        self.f_timer.timeout.connect(self.frame_timer)

        self.cur_cmnd = STOP_CMND

        self.stopButton.setEnabled(False)

        self.startButton.clicked.connect(self.start)
        self.stopButton.clicked.connect(self.stop)
        self.quitButton.clicked.connect(self.quit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OperVu Automated SI Tracker"))
        self.label.setText(_translate("MainWindow", "OR Video with Tracked SIs"))
        self.label_3.setText(_translate("MainWindow", "0.5"))
        self.label_4.setText(_translate("MainWindow", "0.0"))
        self.label_5.setText(_translate("MainWindow", "0.5"))
        self.label_6.setText(_translate("MainWindow", "1.0"))
        self.label_7.setText(_translate("MainWindow", "1.0"))
        self.label_2.setText(_translate("MainWindow", "Detected and Tracked SIs"))
        self.label_8.setText(_translate("MainWindow", "IN"))
        self.label_9.setText(_translate("MainWindow", "Inferred"))
        self.label_10.setText(_translate("MainWindow", "Track ID"))
        self.label_11.setText(_translate("MainWindow", "Name"))
        self.label_12.setText(_translate("MainWindow", "Center"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.stopButton.setText(_translate("MainWindow", "STOP"))
        self.quitButton.setText(_translate("MainWindow", "QUIT"))

    def start(self):
        self.startButton.setEnabled(False)
        self.quitButton.setEnabled(False)
        self.stopButton.setEnabled(True)
        while not status_q.empty():
            status_q.get()
        cmnd_q.put(START_CMND)
        self.cur_cmnd = START_CMND
        self.f_timer.start()

    def frame_timer(self):
        if self.cur_cmnd == STOP_CMND:
            self.f_timer.stop()
        while status_q.empty():
            return
        image = status_q.get()
        siInfo = status_q.get()
        # if images == STOP_CMND:
            # self.stop()
            # return

        # qimg = QtGui.QImage(image[0].get_image_data(),image[0].width,
                # image[0].height, image[0].line_pitch, QtGui.QImage.Format_RGB888)
        qimg = QtGui.QImage(image, image.shape[0], image.shape[1], QtGui.QImage.Format_RGB888)
        pixmap = QtGui.QPixmap(qimg)
        pixmap = pixmap.scaled(self.video.width(), self.video.height(), QtCore.Qt.KeepAspectRatio) # Scale pixmap
        self.video.setPixmap(pixmap) # Set the pixmap onto the label

        self.inText.setText(siInfo['in'])
        self.inferredText.setText(siInfo['cov'])
        self.trackIdText.setText(siInfo['id'])
        self.nameText.setText(siInfo['si'])
        self.centerText.setText(siInfo['cen'])

    def stop(self):
        if self.cur_cmnd == START_CMND:
            self.f_timer.stop()
        self.stopButton.setEnabled(False)
        self.startButton.setEnabled(True)
        self.quitButton.setEnabled(True)
        cmnd_q.put(STOP_CMND)
        self.cur_cmnd = STOP_CMND

    def quit(self):
        cmnd_q.put(QUIT_CMND)
        app.quit()




if __name__ == "__main__":
    import sys

    t = threading.Thread(target=det_n_trk.detect_and_predict, args=(cmnd_q, status_q))
    t.start()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
